### ISSUE TITLE
1.15.2 QA Checklist

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Conquest-Reforged-Resourcepack#28]
- [x] **Either remove or add biome specific buttons as separate blocks and replace current buttons with normal textures/models**
- [x] **Change some fences and various fence mechanic blocks (hanging food) to start as a pane**
- [x] **Remove 1 Roman door block and turn texture into additional door** (phil)
- [x] **Edit inventory models for better visual consistency** (see #31)
- [x] **Remove one of each limestone/sandstone lapis block** (phil)
- [x] **Make dokimeion blue marble less dark and more sky blue**
- [x] **Large light limestone brick (make new texture + CTM)**
- [x] **Combine White Painted Wood Trellis/Fence in C menu**
- [x] **Change leaf inventory models to just use side texture**
- [x] **Orange sandstone cobble (too aggressive coloration)**
- [x] **Wooden support frame rotatable all directions** (phil)
- [x] **Red/brown sandstone cobble (contrast + top CTM**
- [x] **Circular carved design rework limestone/granite**
- [x] **Update enchanting table model** (element count)
- [x] **Rework Shoji** (additional shojis in the ctm folder)
- [x] **Large andesite brick (make new texture + CTM)**
- [x] **Blackberry/sweet berry bush color too bright**
- [x] **Fancy blue marble design guilded texture**
- [x] **Retexture dwarven design blocks** (whee?)
- [x] **Redo animal model to use barrier system**
- [x] **Gothic sandstone column texture rework**
- [x] **Update lever models** (element count)
- [x] **Update elven pillar textures** (whee?)
- [x] **Add iron bar/cell/cage slab models**
- [x] **Add pillar model for pillar blocks**
- [x] **Update asphalt with line texture**
- [x] **Beech leaves still walkthrough**
- [x] **Polychrome blocks rework**
- [x] **Woven granite rework**
- [x] **Torch with grille scale**
- [x] **Moss/lichen textures**
- [x] **Remove Mandrake**
- [x] **Organize tabs**
- [x] Rework baroque wallpapers
- [x] Fancy table rework
- [x] Rework ship lantern
- [x] Fleur-de-lis rework
- [x] Rework Phil plasters with bright colors
- [x] Urn rework
- [x] Simple marble column design rework
- [x] Fancy arch bookshelf rework
- [x] Granite art window rework
- [x] Simple arch window rework
- [x] Rework slate tiles (sharpness)
- [x] Hobbit window rework + CTM
- [x] Brown red wood shingles bleach color
- [x] Fancy birch wood panel rework
- [x] Rework red clay beaver tiles
- [x] Concrete textures
- [x] Orange/dark red clay shingles rework (nb: was given names for these by whee so they should be clay afaik)
- [x] Circular carved granite design
- [x] Stripped birch connection
- [x] fancy birch arch panel
- [x] Smooth marble column
- [x] Rework bones on the ground
- [x] Tweak new rail textures to be more worn
- [x] Phil painted marble textures rework
- [x] Stucco arch design vertical CTM
- [x] Fancy cabinet rework
- [x] Rail rework/3D model
- [x] Arabian window rework
- [x] Burnt sienna stucco arch blurry
- [x] Worn yellow/peach plaster rework
- [x] Wooden Telescope 3D model
- [x] Add new paintings from RP
- [x] Fancy shelf rework
- [x] Skinny shutter rework shading
- [x] Yellow/brown/white/light gray/ carpet CTM
- [x] Rework insect textures
- [x] Leaf on the ground random or CTM
- [x] Scaffolding rework
- [x] Rough marble rework
- [x] Blue tudor rework
- [x] Gold block rework
- [x] Rework thatch shadows
- [x] Icy covered limestone top CTM
- [x] Sandstone debris rework
- [x] Rework hay bales
- [x] Burlap rework
- [x] Ash log update
- [x] Wicker basket colors
- [x] Goat sallow top texture/CTM
- [x] Red and blue stripe clay mud wall rework
- [x] Red masonry line block reworks
- [x] Tree decorated window shading
- [x] Wooden pole 3D model
- [x] Cannon block rework
- [x] Schist CTM
- [x] Firewood top CTM
- [x] Add mossy goat sallow log
- [x] Add mossy olive log
- [x] Carts collision box
- [x] Mallorn CTM
- [x] Run mosaics through CTM converter
- [x] Small marble diagonal checker pattern rework
- [x] Weird blue line rowan log connection
- [x] Orange stucco diamond rework
- [x] Telescope 3D model
- [x] Blue marble column guilded texture
- [x] Rack of tongs and hammers chain texture bug
- [x] Add fish trap waterlogged state
- [x] Remove wax from redstone repeater/comparator
- [x] Paper lantern 3D model
- [x] Asphalt rework
- [x] Rename gray concrete to asphalt
- [x] Coal on the ground add CTM
- [x] Fodder rework/CTM
- [x] Fix balustrade connections
- [x] Look into #4

**Comment by HIPPOKLEIDES** [comment]
Bolded those which I think would be most important for beta/release, based on what seems to potentially require the most drastic changes and what is used most often in large quantity
